### ISSUE TITLE
Planned features for 202312 milestone

### ISSUE THREAD

**Issue by xen0n** [ruyisdk/ruyi#1]
* [ ] Self management
    * [ ] `ruyi self update`
    * [ ] `ruyi self uninstall`
* [ ] Toolchain updating
* [ ] Local state cache (tracking installed status of packages etc.)
