### ISSUE TITLE
0.3 release planning

### ISSUE THREAD

**Issue by xen0n** [ruyisdk/ruyi#29]
* [x] `ruyi news` #31
* [x] External distfiles fetching #37
* [x] System image packages #37
* [x] ~`ruyi self update`~ #34; deferred to 0.4
* [x] `ruyi device provision` #36

**Comment by xen0n** [comment]
Feature development done, awaiting PM and QA approval for the final release.

**Comment by xen0n** [comment]
https://github.com/ruyisdk/ruyi/releases/tag/0.3.0
